echo "----------------A-1.cmm---------------"
./parser ../Test/A-1.cmm
echo "----------------A-2.cmm---------------"
./parser ../Test/A-2.cmm
echo "----------------A-3.cmm---------------"
./parser ../Test/A-3.cmm
echo "----------------A-4.cmm---------------"
./parser ../Test/A-4.cmm
echo "----------------A-5.cmm---------------"
./parser ../Test/A-5.cmm
echo "----------------A-6.cmm---------------"
./parser ../Test/A-6.cmm
echo "----------------A-7.cmm---------------"
./parser ../Test/A-7.cmm
echo "----------------A-8.cmm---------------"
./parser ../Test/A-8.cmm
echo "----------------A-9.cmm---------------"
./parser ../Test/A-9.cmm
echo "----------------A-10.cmm---------------"
./parser ../Test/A-10.cmm
echo "----------------A-11.cmm---------------"
./parser ../Test/A-11.cmm
echo "----------------A-12.cmm---------------"
./parser ../Test/A-12.cmm
echo "----------------A-13.cmm---------------"
./parser ../Test/A-13.cmm
echo "----------------A-14.cmm---------------"
./parser ../Test/A-14.cmm
echo "----------------A-15.cmm---------------"
./parser ../Test/A-15.cmm
echo "----------------A-16.cmm---------------"
./parser ../Test/A-16.cmm
echo "----------------A-17.cmm---------------"
./parser ../Test/A-17.cmm
echo "----------------A-18.cmm---------------"
./parser ../Test/A-18.cmm
echo "----------------A-19.cmm---------------"
./parser ../Test/A-19.cmm
echo "----------------A-20.cmm---------------"
./parser ../Test/A-20.cmm
echo "----------------B-1.cmm---------------"
./parser ../Test/B-1.cmm
echo "----------------B-2.cmm---------------"
./parser ../Test/B-2.cmm
echo "----------------C-1.cmm---------------"
./parser ../Test/C-1.cmm
echo "----------------C-2.cmm---------------"
./parser ../Test/C-2.cmm
